### ISSUE TITLE
Is there an interest to support Systems Biology Graphical Notation (SBGN)?

### ISSUE THREAD

**Issue by GeorgeS2019** [fslaborg/Cyjs.NET#6]
The project [site](https://sbgn.github.io/)
An example: https://github.com/iVis-at-Bilkent/sbgnviz.js 

![image](https://user-images.githubusercontent.com/49812372/139527099-489299b3-1a05-44c8-b9d8-2bf96a061e59.png)

**Comment by muehlhaus** [comment]
I am very sorry. I missed your question. Are you working on SBGNViz?

**Comment by GeorgeS2019** [comment]
I think the same users interested in Cyjs.NET will also be interested in SBGNViz. 

Currently, the way SBGNViz is implemented is not as portable as cytoscape.js, IN MY view. 

Answer: , evaluated the feasibility,  not doing it that NOW.

**Comment by GeorgeS2019** [comment]
@kMutagene 

Kelvin, 
If you have interest, SBGN for .NET is urgently needed.
