### ISSUE TITLE
Attempt for BlazorCyjs

### ISSUE THREAD

**Issue by GeorgeS2019** [fslaborg/Cyjs.NET#8]
Thank you for creating Cyjs.NET, I am learning the concepts and use that to bring that to Blazor

For users who would like to [try](https://github.com/sps014/BlazorBindGen/issues/2#issuecomment-1214141346)

![msedge_lahSYjk5ug](https://user-images.githubusercontent.com/49812372/184487607-dab45f46-dd4b-468f-bfc7-84c66279bd98.gif)

**Comment by muehlhaus** [comment]
Hi George,
the graphs should be interactive by default. If you have a look at the example https://fslab.org/Cyjs.NET/example.html
you should be able to move the notes. Does this help?

I am looking forward to see this in Blazor. :)

**Comment by GeorgeS2019** [comment]
@muehlhaus  The animated gif above is DONE in Blazor. 

Now I am looking into Cyjs.NET (F#) code to figure out how best to integrate that to make the .NET Cyjs.NET work in Blazor. 

I think it is possible to do the complex graph in Blazor, however ,  it is not an element solution yet.

**Comment by kMutagene** [comment]
For future reference, The process of getting thi lib to work in Blazor is equivalent to Plotly.NET: https://github.com/kMutagene/Plotly.NET.BlazorSample
